apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: iot-system
data:
  AWS_IOT_ENDPOINT: "a2s082f26l8xct-ats.iot.us-east-1.amazonaws.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: iot-system
type: Opaque
# Using base64 encoded values instead of plaintext stringData
data:
  # The actual value will be created and managed separately
  # DATABASE_URL will be populated using kubectl or a secure CI/CD process
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-service-python
  namespace: iot-system
  labels:
    app: mqtt-service-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqtt-service-python
  template:
    metadata:
      labels:
        app: mqtt-service-python
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3001"
    spec:
      containers:
      - name: mqtt-service-python
        image: 997820552516.dkr.ecr.us-east-1.amazonaws.com/iot-collector-dev-mqtt-service-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        - name: PORT
          value: "3001"
        - name: AWS_IOT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: mqtt-config
              key: AWS_IOT_ENDPOINT
        volumeMounts:
        - name: mqtt-certs
          mountPath: /app/certs
          readOnly: true
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 2
      volumes:
      - name: mqtt-certs
        secret:
          secretName: mqtt-certs
# ... rest of code remains same