version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    
  mqtt-service:
    build:
      context: .
      dockerfile: docker/mqtt-service/Dockerfile
    depends_on:
      - postgres
      - mqtt-broker
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/iot_data
    ports:
      - "3001:3001"
    
  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/iot_data
    ports:
      - "3000:3000"

volumes:
  postgres_data:
