persistence:
  enabled: false

service:
  type: LoadBalancer

adminPassword: "${GRAFANA_ADMIN_PASSWORD}"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    mqtt-dashboard:
      json: |
        {
          "title": "IoT Metrics",
          "panels": [],
          "schemaVersion": 26,
          "version": 1
        }
