apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-service
  namespace: iot-system
  labels:
    app: mqtt-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-service
  template:
    metadata:
      labels:
        app: mqtt-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3001"
    spec:
      containers:
      - name: mqtt-service
        image: 997820552516.dkr.ecr.us-east-1.amazonaws.com/iot-collector-dev-mqtt-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        - name: MQTT_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: mqtt-config
              key: MQTT_BROKER_URL
        - name: MQTT_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: mqtt-config
              key: MQTT_CLIENT_ID
        - name: MQTT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: mqtt-config
              key: MQTT_TOPIC
        - name: PORT
          value: "3001"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: iot-system
  labels:
    app: mqtt-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3001"
spec:
  selector:
    app: mqtt-service
  ports:
  - port: 80
    targetPort: 3001
    name: http
  type: ClusterIP
