apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: iot-system
data:
  mqtt-broker-url: "mqtt://mqtt-broker:1883"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: iot-system
type: Opaque
stringData:
  database-url: "postgres://postgres:postgres@postgres:5432/iot_data"
