apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-service
  labels:
    app: mqtt-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqtt-service
  template:
    metadata:
      labels:
        app: mqtt-service
    spec:
      containers:
      - name: mqtt-service
        image: iot-collector/mqtt-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: MQTT_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mqtt-broker-url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-url
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  labels:
    app: mqtt-service
spec:
  selector:
    app: mqtt-service
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP